### ISSUE TITLE
TODO transferred from staged-recipes/libssh2

### ISSUE THREAD

**Issue by shadowwalkersb** [conda-forge/libssh2-feedstock#1]
- [ ] See [Customizing the build](https://github.com/libssh2/libssh2/blob/master/docs/INSTALL_CMAKE#L33)
- [ ] How is `openssl` linked, https://github.com/conda-forge/staged-recipes/pull/1757#discussion_r83076627?
- [ ] Do they need certificates provided? ( https://github.com/conda-forge/staged-recipes/pull/1757#discussion_r83076627 ) ref: https://curl.haxx.se/docs/sslcerts.html ( https://github.com/conda-forge/staged-recipes/pull/1757#discussion_r83125667 )
- [ ] Switch to NMake, see https://github.com/conda-forge/staged-recipes/pull/1757#issuecomment-253371802 and https://github.com/conda-forge/staged-recipes/pull/1757#issuecomment-253625679

**Comment by ocefpaf** [comment]
Closing this as stale.
